In [2]:
%pip install pandas numpy matplotlib seaborn openpyxl

Requirement already satisfied: pandas in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (2.5.3)
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp312-cp312-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: openpyxl in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (from pandas) (2026.4)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.67.0-cp312-cp312-win_amd64.whl.metadata (139 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (from matplotlib) (26.0)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-13.0.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: et-xmlfile in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading matplotlib-3.11.2-cp312-cp312-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.3 MB 7.6 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.3 MB 9.1 MB/s eta 0:00:01
   ---------------------------- ----------- 6.6/9.3 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 11.6 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.4.0-cp312-cp312-win_amd64.whl (234 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.67.0-cp312-cp312-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 17.9 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp312-cp312-win_amd64.whl (70 kB)
Downloading pillow-13.0.0-cp312-cp312-win_amd64.whl (7.3 MB)
   ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
   ------------------------------ --------- 5.5/7.3 MB 25.8 MB/s eta 0:00:01
   ---------------------------------------- 7.3/7.3 MB 24.9 MB/s  0:00:00
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/8 [pyparsing]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.67.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\New Recordings\Udemy\Data analyst Bootcamp\Python\venv\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

# Using the libarys to give me the following abilitys
- **Pandas:** Loads and analyses data.
- **NumPy:** Performs numerical calculations.
- **Matplotlib:** Creates charts and graphs.
- **Seaborn:** Creates statistical visualisations.

In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the Dataset
The employment dataset for May 2023 is loaded into a Pandas DataFrame called dataset for further analysis.

In [7]:
dataset=pd.read_excel('all_data_M_2023.xlsx')

# Exploring the Dataset
The first 10 rows are diplayed to understand the datasets structure and identify the available variables

In [10]:
dataset.head(10)

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,23.11,37.01,58.4,29050,35660,48060,76980,121470,NaN,NaN
1,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,56.19,81.29,111.36,54550,78330,116880,169090,231620,NaN,NaN
2,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,49.74,79.57,#,46400,66170,103460,165500,#,NaN,NaN
3,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
4,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
5,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1020,General and Operations Managers,...,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
6,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
7,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1030,Legislators,...,*,*,*,21010,28810,47290,82200,129510,True,NaN
8,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1031,Legislators,...,*,*,*,21010,28810,47290,82200,129510,True,NaN
9,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-2000,"Advertising, Marketing, Promotions, Public Rel...",...,67.23,96.15,#,69170,99180,139850,199990,#,NaN,NaN

## Dataset Structure

The dataset structure is examined to determine the number of records and variables available for analysis. This information helps assess the dataset and identify the variables relevant to the research objectives.

In [14]:
##as you can see bellow, the raw and the columns  
dataset.shape

(413327, 32)

In [16]:
## In this one you can see the 
dataset.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='str')

## Describing the Dataset

The `describe()` function helps us understand the numerical data by providing a statistical summary. It shows information such as the average, minimum and maximum values, and how the data is distributed. This gives us an initial overview of the dataset before moving on to the analysis.

In [18]:
dataset.describe()

               AREA      AREA_TYPE       OWN_CODE
count  4.133270e+05  413327.000000  413327.000000
mean   3.784693e+05       2.766826     717.279984
std    1.135906e+06       1.780825     601.852382
min    1.000000e+00       1.000000       1.000000
25%    9.900000e+01       1.000000       5.000000
50%    9.900000e+01       2.000000    1235.000000
75%    3.710000e+04       4.000000    1235.000000
max    7.800001e+06       6.000000    1235.000000

## Dataset Information

The info() method provides an overview of the dataset

In [20]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 413327 entries, 0 to 413326
Data columns (total 32 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AREA          413327 non-null  int64
 1   AREA_TITLE    413327 non-null  str
 2   AREA_TYPE     413327 non-null  int64
 3   PRIM_STATE    413327 non-null  str
 4   NAICS         413327 non-null  str
 5   NAICS_TITLE   413327 non-null  str
 6   I_GROUP       413327 non-null  str
 7   OWN_CODE      413327 non-null  int64
 8   OCC_CODE      413327 non-null  str
 9   OCC_TITLE     413327 non-null  str
 10  O_GROUP       413327 non-null  str
 11  TOT_EMP       413327 non-null  object
 12  EMP_PRSE      413327 non-null  object
 13  JOBS_1000     235826 non-null  object
 14  LOC_QUOTIENT  235826 non-null  object
 15  PCT_TOTAL     170470 non-null  object
 16  PCT_RPT       170470 non-null  object
 17  H_MEAN        413327 non-null  object
 18  A_MEAN        413327 non-null  object
 19  MEAN_PRSE     413327 non-null  object
 20  H_PCT10       413327 non-null  object
 21  H_PCT25       413327 non-null  object
 22  H_MEDIAN      413327 non-null  object
 23  H_PCT75       413327 non-null  object
 24  H_PCT90       413327 non-null  object
 25  A_PCT10       413327 non-null  object
 26  A_PCT25       413327 non-null  object
 27  A_MEDIAN      413327 non-null  object
 28  A_PCT75       413327 non-null  object
 29  A_PCT90       413327 non-null  object
 30  ANNUAL        16497 non-null   object
 31  HOURLY        755 non-null     object
dtypes: int64(3), object(21), str(8)
memory usage: 100.9+ MB

## Selecting Columns from the Dataset

Selecting columns helps us focus on the information needed for the analysis. By examining the available columns, we can identify the variables relevant to employment and occupation comparisons.

In [21]:
dataset.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='str')

## Identifying Relevant Occupations

The next step is to identify occupations related to Artificial Intelligence, Data Science, and Software Development. This will help narrow the dataset to information relevant to the research objectives.

In [23]:
dataset['OCC_TITLE'].head(20)

0                                       All Occupations
1                                Management Occupations
2                                        Top Executives
3                                      Chief Executives
4                                      Chief Executives
5                       General and Operations Managers
6                       General and Operations Managers
7                                           Legislators
8                                           Legislators
9     Advertising, Marketing, Promotions, Public Rel...
10                  Advertising and Promotions Managers
11                  Advertising and Promotions Managers
12                         Marketing and Sales Managers
13                                   Marketing Managers
14                                       Sales Managers
15            Public Relations and Fundraising Managers
16                            Public Relations Managers
17                                 Fundraising Managers
18                      Operations Specialties Managers
19      Administrative Services and Facilities Managers
Name: OCC_TITLE, dtype: str